#!/bin/bash
for morse in a b c d e f g h h i j k l m n o p q r s t u v w x y z 0 1 2 3 4 5 6 7 8 9 , . ? \!
do
  echo $morse
  echo $morse  | cwwav-master/cwwav -f 800 -w 25 -o sounds/"$morse.wav"

done
